"$schema" = "../gen/schemas/desktop-schema.json"

[[permission]]
identifier = "allow-import-data-dialog"
description = "Allows the import_data_dialog command."
commands.allow = ["import_data_dialog"]
